# frozen_string_literal: true

source "https://rubygems.org"

gem "bundler", "2.1.4"

# Make sure to load ActiveSupport before sinatra to allow its IndifferentHash
# to be loaded if needed.
gem "activesupport", "6.0.3.4", require: "active_support/all"

gem "rake", "13.0.1"

# Framework
gem "sinatra", "2.1.0", require: "sinatra/base"
gem "sinatra-contrib", "2.1.0"

# Extensions
gem "rack-protection", "2.1.0"

# Content parsing
gem "kramdown", "2.3.0"

# I18n fun
gem "http_accept_language", "2.1.1"
gem "i18n", "1.8.5"

group :development do
  # To make running puma and the webpack dev server together easier
  gem "foreman", "0.87.2"

  # Linters
  gem "pronto", "0.10.0", require: false
  gem "pronto-rubocop", "0.10.0", require: false
  gem "pronto-scss", "0.10.0", require: false
  gem "rubocop", "0.85.1", require: false
end

group :production do
  gem "redis", "4.2.2"
end

# Deployment
gem "puma", "5.0.4"
