# frozen_string_literal: true

source "https://rubygems.org"

# Make sure to load ActiveSupport before sinatra to allow its IndifferentHash
# to be loaded if needed.
gem "activesupport", "5.2.3", require: "active_support/all"

gem "rake", "12.3.2"

# Framework
gem "sinatra", "2.0.5", require: "sinatra/base"
gem "sinatra-contrib", "2.0.5"

# Extensions
gem "rack-protection", "2.0.5"

# Asset pipeline
gem "sinatra-asset-pipeline", "2.2.0", require: "sinatra/asset_pipeline"
gem "sprockets-es6", "0.9.2", require: "sprockets/es6"
gem "uglifier", "4.1.20"

# Content parsing
gem "kramdown", "2.1.0"

# I18n fun
gem "http_accept_language", "2.1.1"
gem "i18n", "1.6.0"

group :development do
  # Linters
  gem "pronto", "0.10.0", require: false
  gem "pronto-rubocop", "0.10.0", require: false
  gem "pronto-scss", "0.10.0", require: false
  gem "rubocop", "0.67.2", require: false
end

group :production do
  gem "redis", "4.1.0"
end

source "https://rails-assets.org" do
  gem "rails-assets-bootstrap", "4.3.1"
  gem "rails-assets-handlebars", "4.1.2"
  gem "rails-assets-jquery", "3.4.0"
  gem "rails-assets-popper.js", "1.15.0"
end

# Deployment
gem "puma", "3.12.1"
