# frozen_string_literal: true

require_relative "./environment"
require_relative "./server"

require "sinatra/asset_pipeline/task"
Sinatra::AssetPipeline::Task.define! Server

Dir[File.join(__dir__, "lib", "tasks", "*.rake")].each {|file| import file }
